### ISSUE TITLE
Error when running !events:  UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by BadWolf0081** [versx/PoGoEventWatcher#14]
I am getting the following error when I try to run !events.  Any help is appreciated.

```(node:631460) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/username/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/home/username/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/home/username/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/home/username/EventWatcher/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/home/username/EventWatcher/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/home/username/EventWatcher/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at /home/username/EventWatcher/dist/commands/events.js:64:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/username/EventWatcher/dist/commands/events.js:5:58)
(node:631460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
```

**Comment by versx** [comment]
> I am getting the following error when I try to run !events. Any help is appreciated.
> 
> ```
>     at Function.normalizeFields (/home/username/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
>     at MessageEmbed.setup (/home/username/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
>     at new MessageEmbed (/home/username/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
>     at embedLikes.map.e (/home/username/EventWatcher/node_modules/discord.js/src/structures/APIMessage.js:166:40)
>     at Array.map (<anonymous>)
>     at APIMessage.resolveData (/home/username/EventWatcher/node_modules/discord.js/src/structures/APIMessage.js:166:31)
>     at TextChannel.send (/home/username/EventWatcher/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
>     at /home/username/EventWatcher/dist/commands/events.js:64:25
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/username/EventWatcher/dist/commands/events.js:5:58)
> (node:631460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
> ```

Still an issue on latest?
