### ISSUE TITLE
"webhooks": [],

### ISSUE THREAD

**Issue by mimikq** [versx/PoGoEventWatcher#9]
in configuration is missing that webhook should be in 

"webhooks": [""],

and not : 

 "webhooks": [],

**Comment by versx** [comment]
It should be an empty array as it is in the config. `[]`
_Edit:_ I see your confusion, yes the webhook needs to wrapped in double quotes. i.e:
```
"webhooks": ["http://webhook.site/jkjlkjlkjlkjkl"],
```

**Comment by mimikq** [comment]
> It should be an empty array as it is in the config. `[]`
> _Edit:_ I see your confusion, yes the webhook needs to wrapped in double quotes. i.e:
> 
> ```
> "webhooks": ["http://webhook.site/jkjlkjlkjlkjkl"],
> ```
yes i set it up without "" and i got error `SyntaxError: /EventWatcher/src/config.json: Unexpected token h in JSON at position 296`

and took me a while to find where is the issue me not too much familiar with coding. 

and also where i can ask for help please, i'm trying to get it works but in some point i dot error with permissions


(node:21259) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.setup (/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:78:91)
    at new MessageEmbed (/EventWatcher/node_modules/discord.js/src/structures/MessageEmbed.js:18:10)
    at embedLikes.map.e (/EventWatcher/node_modules/discord.js/src/structures/APIMessage.js:166:40)
    at Array.map (<anonymous>)
    at APIMessage.resolveData (/EventWatcher/node_modules/discord.js/src/structures/APIMessage.js:166:31)
    at TextChannel.send (/EventWatcher/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:166:62)
    at postActiveEvents (/EventWatcher/src/commands/events.js:129:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:21259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 

bot is able to answer to cmd events #room but when i run events #room active i got this error and me bit lost .

edit: leave it we fix it it was old version of node.js :( 


thanks in advance

**Comment by mimikq** [comment]
i want to ask if it is working good because tool create voice room for event but not new notification.

![image](https://user-images.githubusercontent.com/3299474/106614796-0b932c80-656c-11eb-8799-5d15e1679f3a.png)

where i can ask for more help ? 

thanks

**Comment by clburlison** [comment]
https://discord.gg/zZ9h9Xa
